### ISSUE TITLE
ks plugin cluster services command line parameters 

### ISSUE THREAD

**Issue by ebullient** [IBM-Bluemix-Docs/container-service-cli-plugin#1]
https://cloud.ibm.com/docs/container-service-cli-plugin?topic=container-service-cli-plugin-kubernetes_service_cli_plugin#cluster_services_commands .. 

create/remove of service use different terms for the service parameter (SERVICE_INSTANCE_NAME .. SERVICE_INSTANCE_GUID). They _seem_ to be talking about the same thing, though one is qualified more than the other is.

**Comment by Nadine2016** [comment]
@ebullient we have changed this section in our CLI reference and it will be pushed to prod with our next prod push. The changes will appear here: https://cloud.ibm.com/docs/containers?topic=containers-cs_cli_reference#cs_cli_reference

We are working on getting our content published in this location as well. Closing this issue. Thanks for pointing that out!
